const cards = [
    { id: 1, name: "Ás de Copas", value: 11 },
    { id: 2, name: "Dois de Copas", value: 0 },
    { id: 3, name: "Três de Copas", value: 0 },
    { id: 4, name: "Quatro de Copas", value: 0 },
    { id: 5, name: "Cinco de Copas", value: 0 },
    { id: 6, name: "Seis de Copas", value: 0 },
    { id: 7, name: "Sete de Copas", value: 10 },
    { id: 8, name: "Valete de Copas", value: 3 },
    { id: 9, name: "Dama de Copas", value: 2 },
    { id: 10, name: "Rei de Copas", value: 4 },
    { id: 11, name: "Ás de Espadas", value: 11 },
    { id: 12, name: "Dois de Espadas", value: 0 },
    { id: 13, name: "Três de Espadas", value: 0 },
    { id: 14, name: "Quatro de Espadas", value: 0 },
    { id: 15, name: "Cinco de Espadas", value: 0 },
    { id: 16, name: "Seis de Espadas", value: 0 },
    { id: 17, name: "Sete de Espadas", value: 10 },
    { id: 18, name: "Valete de Espadas", value: 3 },
    { id: 19, name: "Damade Espadas", value: 2 },
    { id: 20, name: "Rei de Espadas", value: 4 },
    { id: 21, name: "Ás de Ouros", value: 11 },
    { id: 22, name: "Dois de Ouros", value: 0 },
    { id: 23, name: "Três de Ouros", value: 0 },
    { id: 24, name: "Quatro de Ouros", value: 0 },
    { id: 25, name: "Cinco de Ouros", value: 0 },
    { id: 26, name: "Seis de Ouros", value: 0 },
    { id: 27, name: "Sete de Ouros", value: 10 },
    { id: 28, name: "Valete de Ouros", value: 3 },
    { id: 29, name: "Dama de Ouros", value: 2 },
    { id: 30, name: "Rei de Ouros", value: 4 },
    { id: 31, name: "Ás de Paus", value: 11 },
    { id: 32, name: "Dois de Paus", value: 0 },
    { id: 33, name: "Três de Paus", value: 0 },
    { id: 34, name: "Quatro de Paus", value: 0 },
    { id: 35, name: "Cinco de Paus", value: 0 },
    { id: 36, name: "Seis de Paus", value: 0 },
    { id: 37, name: "Sete de Paus", value: 10 },
    { id: 38, name: "Valete de Paus", value: 3 },
    { id: 39, name: "Dama de Paus", value: 2 },
    { id: 40, name: "Rei de Paus", value: 4 },
];

module.exports = cards;

module.exports = cards;